### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ghost** [AdamGitFun/prj-rev-bwfs-dasmoto#4]
Grade: Meets Expectations
Great job with the layout and design of the website! Your code is also well-written and clean. For improvement, you can add more comments to the code. In addition, your img elements can have alt attributes. As a further challenge, consider adding more pages to the website and creating a drop down menu. This will take some additional research, but I think it will be a neat challenge to work on! Based on your work here, I think you are ready for it!

**Comment by AdamGitFun** [comment]
Interesting. I have this sort of working with select and the onchange attribute.  It automatically changes the page when a new option is selected but it won't allow the Home option to be chosen since it's already pre-selected. Actually, I now have a work around but it feels clunky. New code pasted below.

**Comment by AdamGitFun** [comment]
`<select onchange="location = this.options[this.selectedIndex].value;">
    <option disabled selected value>Home</option>
    <option value="index.html">Home</option>
    <option value="about.html">About</option>
     <option value="contact.html">Contact</option>
</select>`

**Comment by AdamGitFun** [comment]
Note, however, that I had to repeat the same code for select on all three pages.  That feels like a mistake but I'm not sure how to excerpt out a piece of html .
